# Generated by Django 2.2.4 on 2022-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='first_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='dojo',
            old_name='last_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='user',
            new_name='Dojo',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='city',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='state',
        ),
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='null', max_length=90),
            preserve_default=False,
        ),
    ]
