# Generated by Django 2.2.4 on 2022-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_publisher_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
